stages:
  data_ingestion:
    cmd: python src/Kidney/pipeline/stage_1.py
    deps:
      - src/Kidney/pipeline/stage_1.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/kidney-ct-scan-image

  
  prepare_base_model:
    cmd: python src/Kidney/pipeline/stage_2_prepare_base_model.py
    deps:
      - src/Kidney/pipeline/stage_2_prepare_base_model.py
      - config/config.yaml
    params:
      - IMAGE_SIZE
      - INCLUDE_TOP
      - CLASSES
      - WEIGHTS
      - LEARNING_RATE
    outs:
      - artifacts/prepare_base_model

  
  training:
    cmd: python src/Kidney/pipeline/stage_3_model_training.py
    deps:
      - src/Kidney/pipeline/stage_3_model_training.py
      - config/config.yaml
      - artifacts/data_ingestion/kidney-ct-scan-image
      - artifacts/prepare_base_model
    params:
      - IMAGE_SIZE
      - EPOCHS
      - BATCH_SIZE
      - AUGMENTATION
    outs:
      - artifacts/training/model.keras

  evaluation:
    cmd: python src/Kidney/pipeline/stage_4_evaluation.py
    deps:
      - src/Kidney/pipeline/stage_4_evaluation.py
      - config/config.yaml
      - artifacts/data_ingestion/kidney-ct-scan-image
      - artifacts/training/model.keras
    params:
      - IMAGE_SIZE
      - BATCH_SIZE
    metrics:
    - score.json:
        cache: false